### ISSUE TITLE
[SUGESTION] Add demo with custom cell classes

### ISSUE THREAD

**Issue by Zasuk** [ra1028/Carbon#10]
I think a demo with custom cell classes will help some users. 
For example the demo can integrate https://github.com/SwipeCellKit/SwipeCellKit for the cells

**Comment by ra1028** [comment]
@Zasuk 
Currently not supports custom cell class which not inherited from `UITableViewComponentCell` or `UICollectionViewComponentCell`.
I'll probably support it in the future, but haven't yet considered the best API design.

**Comment by wousser** [comment]
I’ll second this. Would like to see the possibility to create a cell node from (custom) UITableViewCell or UICollectionViewCell.

**Comment by ra1028** [comment]
Ok, I'll support it in the future.
I'm still thinking about a better API design for it.

**Comment by ra1028** [comment]
@Zasuk @wousser 
I'm trying to add ability to use custom cell subclass for the container of component.
Draft: https://github.com/ra1028/Carbon/pull/21

**Comment by Zasuk** [comment]
Hi, i haven't tested it yet but the implementation looks ok for me (i was thinking in the same solution). 
Thanks for the hard work and awesome lib
