### ISSUE TITLE
[Request] Loadmore Example with UICollectionView and UITableView

### ISSUE THREAD

**Issue by arimunandar** [ra1028/Carbon#3]
Hi @ra1028 ,

Can you add new Sample for Loadmore with UICollectionView and UITableView please?

I am very interested and love with Carbon, :)

Thanks.

**Comment by dangthaison91** [comment]
@arimunandar Carbon is data-driven UI library. So every change in data will be reflected on UI. If you want to loadmore/expand/collapse your lists, just implement your business logic to change your data source first, Carbon will run the differ to update UI based on your data.

**Comment by ra1028** [comment]
Hi @arimunandar 

I think [TODO app](https://github.com/ra1028/Carbon/blob/master/Examples/Example-iOS/Sources/Todo/TodoViewController.swift) example should help you to understand way to dynamic adding the cells with Carbon.
