### ISSUE TITLE
Why the removal of `UITableViewCellContent` related classes?

### ISSUE THREAD

**Issue by robcas3** [ra1028/Carbon#32]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [x] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

Hi, I appreciate your work but I was wondering: why did you remove `UITableViewCellContent` in the latest release (rc1)? 
It was the only way to access the cell that actually is rendered by the tableview.
Now I can't, for example, add an accessory view to the cell  keeping the cell's background color the same, and I can't make use of the default cell selection behavior.

**Comment by ra1028** [comment]
@robcas3 
You can use arbitrary customized class of cell by overriding UITableViewAdapter implemented in [here](https://github.com/ra1028/Carbon/pull/21)

**Comment by robcas3** [comment]
Oh wow, I missed that PR, sorry!
Thank you, that's what I was looking for!

**Comment by ra1028** [comment]
@robcas3 
Sorry to make some breaking changes without prior notice.
I'll be happy if the new features will help you.
FYI, you can catch up the changes in the versions by checking the release notes.
https://github.com/ra1028/Carbon/releases

**Comment by robcas3** [comment]
@ra1028 
No worries, I was able to adapt to breaking changes in less than 10 mins. 
So it is okay to me!
