### ISSUE TITLE
Option to reload/replace a specific section ID

### ISSUE THREAD

**Issue by Zasuk** [ra1028/Carbon#5]
If we have for example a grouped list with a lot of itens an option to reload only a specific section improves the performance a lot because we don't have to map and regenerate all the components again (for ex when expand/collapsing sections).

Is it possible to get something like this?

**Comment by ra1028** [comment]
How you generate the components is yours.

e.g,
```swift
var fooSection = Section(id: SectionID.foo) {
    didSet { render() }    
}

var barSection = Section(id: SectionID.bar) {
    didSet { render() }
}

func render() {
    renderer.render(
        fooSection,
        barSection
    )
}

 @IBAction func addCellToFooSection() {
    fooSection.cells.append(CellNode(FooComponent()))
}
```

However, the performance of mapping and regenerating components is negligible compared to the rendering performance of View.
So, I recommend a declarative implementation that always regenerates components based on state.
