### ISSUE TITLE
Generic parameter 'H' could not be inferred

### ISSUE THREAD

**Issue by wousser** [ra1028/Carbon#51]
## Checklist
- [x] This is not a Apple's bug.  
- [x] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [x] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

## Expected Behavior
Render Section() with FunctionBuilder Syntax

## Current Behavior
When updating to RC4, rewriting to use FunctionBuilder Syntax, build failed with error:
Generic parameter 'H' could not be inferred for Section(

## Steps to Reproduce
```
Section(
            id: ID.summary,
            header: nil,
            cells: {
                Group(of: state.someContent.enumerated()) { offset, someContent in
                    SampleCell(someContent)
                }
        })
```

## Environments
- Carbon version:
 1.0.0-rc.4

- Swift version:
Apple Swift version 5.1 (swiftlang-1100.0.270.13 clang-1100.0.33.7)

- Xcode version:
Version 11.0 (11A419c)

**Comment by ra1028** [comment]
@wousser 

You must explicitly specify the type of generic parameter or leave out it.
e,g.
```swift
Section(
    id: ID.summary,
    header: Optional<YourHeader>.none,
    cells:  {
    Group(of: state.someContent.enumerated()) { offset, someContent in
        SampleCell(someContent)
    }
)
```
```swift
Section(id: ID.summary) {
    Group(of: state.someContent.enumerated()) { offset, someContent in
        SampleCell(someContent)
    }
}
```

**Comment by wousser** [comment]
Thanks, this implementation differs from RC2 and wasn't clear at first.
