### ISSUE TITLE
Crash when building and launching for iOS 10, 11 and 12 simulator

### ISSUE THREAD

**Issue by Dimillian** [ra1028/Carbon#62]
```
dyld: Library not loaded: /System/Library/Frameworks/SwiftUI.framework/SwiftUI
  Referenced from: /Users/thomasricouard/Library/Developer/CoreSimulator/Devices/A09605A4-9BF2-4D63-9B5A-000D85C18FCA/data/Containers/Bundle/Application/92E5E64B-1EBD-46C3-A9A0-486C122D0E41/Glose Education Staging.app/Frameworks/Carbon.framework/Carbon
  Reason: no suitable image found.  Did find:
	/System/Library/Frameworks/SwiftUI.framework/SwiftUI: mach-o, but not built for iOS simulator
```

SwiftUI is not conditionally linked? I'm getting crash on launch as SwiftUI can't be linked on any earlier iOS version than 13.

**Comment by ra1028** [comment]
Thanks for your report @Dimillian 
That is my mistake in my publishing the release RC5.
I'll fix it on this PR  https://github.com/ra1028/Carbon/pull/63 
Please wait while I release the new version.

**Comment by ra1028** [comment]
@Dimillian 
Just released RC6 with conditionally linking SwiftUI.
Unfortunately, dropped support for Swift5.0 and Xcode10.

**Comment by Dimillian** [comment]
Perfect thanks!
