### ISSUE TITLE
swift package not working

### ISSUE THREAD

**Issue by GINNOV** [ra1028/Carbon#65]
Add Swift Package as per instructions on the read me
https://github.com/ra1028/Carbon

XCode 11+ can't resolve the package for

Error from xcode:
Showing All Messages
: https://github.com/ra1028/Carbon has no Package.swift manifest for version 0.3.0

**Comment by ra1028** [comment]
Hi, @GINNOV .
SwiftPM is introduced in version 1.0.0.rc-1 by https://github.com/ra1028/Carbon/pull/25.
