### ISSUE TITLE
why？when I copy a New Project

### ISSUE THREAD

**Issue by ZW19920614** [ra1028/Carbon#68]
![截屏2019-12-25下午6 05 16](https://user-images.githubusercontent.com/24447161/71442502-24ae9480-2741-11ea-8d14-403c08b6b14e.png)
## Checklist
- [ ] This is not a Apple's bug.  
- [ ] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [ ] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

## Steps to Reproduce

1.
2.
3.
4.

## Environments
- Carbon version:

- Swift version:

- iOS version:

- Xcode version:

- Devices/Simulators:

- CocoaPods/Carthage version:

**Comment by ra1028** [comment]
Hi, @ZW19920614 

I can't guarantee that Carbon works correctly when you modify the source code.
Recommend to install Carbon according to installation in README.
https://github.com/ra1028/Carbon#installation
