### ISSUE TITLE
Create a section that has a rounded corners and shadows.

### ISSUE THREAD

**Issue by waruss321** [ra1028/Carbon#70]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [x] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

## Description
Tried to create the same thing within IGListKit but had no luck. Wondering if anyone has any suggestions as to how to achieve this within Carbon.

https://github.com/Instagram/IGListKit/issues/1313
https://github.com/Instagram/IGListKit/issues/805

**Comment by nonameplum** [comment]
I think the easiest way would be to make png images with the shadow splitted into top/middle/bottom and use it in three separate cell implementations.

**Comment by ra1028** [comment]
@waruss321 

Sorry for my late reply.

As kind contributors to an issue in IGListKit describes, this can be accomplished by custom layout and decoration view.
There is no further support by Carbon.
I close this issue as it's beyond the scope of Carbon features.
