### ISSUE TITLE
What's the difference between these two methods?

### ISSUE THREAD

**Issue by bofeizhu** [ra1028/Carbon#71]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [X] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

What's the difference between these two methods?
``` swift
/// Returns a new instance of `Content`.
///
/// - Returns: A new `Content` instance.
func renderContent() -> Content

/// Render properties into the content.
///
/// - Parameter:
///   - content: An instance of `Content` laid out on the element of list UI.
func render(in content: Content)
```

**Comment by ra1028** [comment]
@bofeizhu 

Sorry for my late reply.

As described in the API doc, it makes an instance by the `renderContent()` method for the first time, and sets the appearance for the instance by the `render(in content: Content)` method, such as color and text.
