### ISSUE TITLE
Need the ability to add event handling to the Component

### ISSUE THREAD

**Issue by BarredEwe** [ra1028/Carbon#75]
## Checklist
- [x] Reviewed the [README](https://github.com/ra1028/Carbon/blob/master/README.md) and [documents](https://ra1028.github.io/Carbon).  
- [x] Searched [existing issues](https://github.com/ra1028/Carbon/issues) for ensure not duplicated.  

## Description
I would like to be able to add event handling directly to the component.

Example:
struct HelloMessage: Component {
    ...
}

HelloMessage().on(.click) { ... }.cellNode
HelloMessage().on(.viewWillAppear) { ... }.cellNode

or

HelloMessage().cellNode.on(.click) { ... }
HelloMessage().cellNode.on(.viewWillAppear) { ... }

## Motivation and Context
Allows you to make ViewController cleaner.

**Comment by ra1028** [comment]
@BarredEwe 

A `Component` cannot have a state because it's a protocol.
It can be implemented by composition, but I don't like it because it complicates the API.

**Comment by BarredEwe** [comment]
I have added this feature for myself. If anyone is interested, I can post a merge request with this feature.
https://github.com/BarredEwe/Carbon/tree/actions

Example:
```

struct TestView: Component {
        ...
}

class TestViewContent: UIView {
        ...
    @IBAction func testButtonTapped(_ sender: UIButton) {
        // Sending actions
        ComponentAction(.custom(.buttonTapped), sender: self).invoke()
    }
}

TestView(...)
        .on(.custom(.buttonTapped)) { action in /*Do something*/ }
        .cellNode

```

**Comment by ra1028** [comment]
Congrats 🎉 
I'll close this issue, but if you have further suggestions, please re-open it.
